REM set PROGRAM_DIR="C:\Program Files\Windows Resource Kits\Tools"
REM SET DEST_FOLDER=Q:\NG_BACKUPS\H
REM SET SOURCE_FOLDER=H:
REM C:
REM CD %PROGRAM_DIR%
REM forfiles -pc:\backups\ipitomy -s -m*.* -c"cmd /c del @FILE" -d-31
REM ROBOCOPY.EXE c:\backups\ h:\backups\ /E /COPYALL /XO /R:2 /W:2 
REM ROBOCOPY.EXE %SOURCE_FOLDER%\ %DEST_FOLDER%\ /E /COPYALL /XO /R:2 /W:2 
SET DEST_FOLDER=F:\NGDC01_BACKUPS\wpdata
SET SOURCE_FOLDER=e:\wpdata
ROBOCOPY.EXE %SOURCE_FOLDER%\ %DEST_FOLDER%\ /E /COPYALL /XO /R:2 /W:2
SET DEST_FOLDER=F:\NGDC01_BACKUPS\src
SET SOURCE_FOLDER=c:\src
ROBOCOPY.EXE %SOURCE_FOLDER%\ %DEST_FOLDER%\ /E /COPYALL /XO /R:2 /W:2
SET DEST_FOLDER=e:\wpdata\src
SET SOURCE_FOLDER=c:\src
ROBOCOPY.EXE %SOURCE_FOLDER%\ %DEST_FOLDER%\ /E /COPYALL /XO /R:2 /W:2
REM System Drive
REM SET DEST_FOLDER=F:\NGDC01_BACKUPS\c-drive\users
REM SET SOURCE_FOLDER=c:\users
REM ROBOCOPY.EXE %SOURCE_FOLDER%\ %DEST_FOLDER%\ /E /COPYALL /XO /R:2 /W:2 REM Update New Windows Server
REM
REM
EXIT